plugins:
  online_user_enabled:
    default: true
    client: true

  online_user_refresh_interval:
    default: 30
    client: true
    description: "How often to refresh the online users list (in seconds)"
    min: 10
    max: 300

  online_user_online_threshold:
    default: 5
    client: false
    description: "How many minutes since last seen to consider a user online"
    min: 1
    max: 60

  online_user_start_collapsed:
    default: true
    client: true
    description: "Start with the sidebar collapsed"

  online_user_show_avatars:
    default: true
    client: true
    description: "Show user avatars in the sidebar"

  online_user_sidebar_width:
    default: 240
    client: true
    description: "Width of the sidebar in pixels"
    min: 200
    max: 400

  online_user_debug:
    default: false
    client: true
    description: "Enable debug logging for usercard interactions"

  online_user_custom_card:
    default: true
    client: true
    description: "Use a custom modal usercard for the online users sidebar instead of the core user card"
